version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/c4k-blog-back/
    overwrite: yes

permissions:
  - object: /home/ec2-user/c4k-blog-back/
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
